config = {
    "bits": [
        {"key": "winddirection", "length": "4"},
        {"key": "windspeed", "length": "6", "max": "63", "min": "0", "step": "1"},
        {"key": "windgusts", "length": "6", "max": "63", "min": "0", "step": "1"},
        {"key": "windspeedBft", "length": "4", "max": "12", "min": "1", "step": "1"},
        {"key": "airpressure", "length": "8", "max": "1155", "min": "900", "step": "1"},
        {
            "key": "temperature",
            "length": "10",
            "max": "49.9",
            "min": "-39.9",
            "step": "0.1",
        },
        {
            "key": "feeltemperature",
            "length": "10",
            "max": "49.9",
            "min": "-39.9",
            "step": "0.1",
        },
        {"key": "humidity", "length": "7", "max": "100", "min": "0", "step": "1"},
        {"key": "service_byte", "length": "5"},
        {"key": "DUMMY_BYTE", "length": "4"},
    ],
    "channel": 0,
    "fallback-station": "6310",
    "frequency": 250000,
    "data_collection_interval": 300,
    "library": "wiringPi",
    "source": "buienradar",
    "stations": {
        "config": {
            0: "6320",
            1: "6321",
            2: "6310",
            3: "6312",
            4: "6308",
            5: "6311",
            6: "6331",
            7: "6316",
        },
        "pins": [3, 4, 5],
    },
}
